TP_Labo4_Final/Models/Cliente.cs
namespace TP_Labo4_Final.Models
{
    public class Cliente
    {
        public int Id { get; set; }
        public string? Nombre { get; set; }
        public string? Apellido { get; set; }
        public string? Cuit { get; set; }
        public string? Direccion { get; set; }
        public string? Altura { get; set; }        
        public string? Departamento { get; set; }
        public string? Piso { get; set; }
        public string? Localidad { get; set; }
        public string? Provincia { get; set; }
        public string? Pais { get; set; }
        public string? Telefono { get; set; }
        public string? Email { get; set; }
        public bool Estado {  get; set; }

        //Clave foranea con viajante
        public int ViajanteId  { get; set; }
        public Viajante? Viajante { get; set; }

        //Relacion uno a muchos con pedidos
        public ICollection<Pedido> ?Pedidos { get; set; }

        //Mostrar nombre completo
        public string NombreCompleto => $"{Nombre} {Apellido}";

    }
}

TP_Labo4_Final/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TP_Labo4_Final.Models;


namespace TP_Labo4_Final.Controllers
{
    public class ClientesController : Controller
    {
        private readonly AppDbContext _context;

        public ClientesController(AppDbContext context)
        {
            _context = context;
        }


        // GET: Clientes
        public async Task<IActionResult> Index(string searchString, int pagina = 1, int tamanioPagina = 5)
        {
            // Obtener los clientes con su respectivo viajante
            var clientes = from c in _context.Clientes
                           .Include(c => c.Viajante)
                           select c;

            // Filtrar por el texto de búsqueda si se proporciona
            if (!String.IsNullOrEmpty(searchString))
            {
                clientes = clientes.Where(s => s.Apellido!.Contains(searchString) || s.Nombre!.Contains(searchString));
            }

            // Obtener el total de clientes (para calcular las páginas)
            var totalClientes = await clientes.CountAsync();

            // Aplicar paginación (omitir los registros anteriores y tomar solo los de la página actual)
            var clientesPaginados = await clientes
                                         .Skip((pagina - 1) * tamanioPagina)
                                         .Take(tamanioPagina)
                                         .ToListAsync();

            // Crear el paginador con la lista paginada
            var paginador = new Paginador<Cliente>(clientesPaginados, totalClientes, pagina, tamanioPagina);

            //Para mantener el valor del campo de búsqueda cuando el usuario cambie de página
            ViewData["searchString"] = searchString;
            return View(paginador);
        }


        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .Include (c => c.Viajante)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            ViewData["ViajanteId"] = new SelectList(_context.Viajantes, "Id", "Nombre");
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,Cuit,Direccion,Altura,Departamento,Piso,Localidad,Provincia,Pais,Telefono,Email,Estado,ViajanteId")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                
                // Verificar que el viajante existe
                var viajante = await _context.Viajantes.FindAsync(cliente.ViajanteId);

                if (viajante == null)
                {
                    ModelState.AddModelError("ViajanteId", "El viajante seleccionado no existe.");                    
                    ViewData["ViajanteId"] = new SelectList(_context.Viajantes, "Id", "Nombre", cliente.ViajanteId);
                    return View(cliente);
                }

                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ViajanteId"] = new SelectList(_context.Viajantes, "Id", "Nombre");
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            ViewData["ViajanteId"] = new SelectList(_context.Viajantes, "Id", "Nombre");
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellido,Cuit,Direccion,Altura,Departamento,Piso,Localidad,Provincia,Pais,Telefono,Email,Estado,ViajanteId")] Cliente cliente)
        {
            if (id != cliente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var viajante = await _context.Viajantes.FindAsync(cliente.ViajanteId);
                    if (viajante == null)
                    {
                        ModelState.AddModelError("ViajanteId", "El viajante seleccionado no existe.");
                        ViewData["ViajanteId"] = new SelectList(_context.Viajantes, "Id", "Nombre", cliente.ViajanteId);
                    }
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["ViajanteId"] = new SelectList(_context.Viajantes, "Id", "Nombre", cliente.ViajanteId);
           
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente != null)
            {
                _context.Clientes.Remove(cliente);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
            return _context.Clientes.Any(e => e.Id == id);
        }
    }
}

TP_Labo4_Final/Controllers/ImportarExController.cs
using ClosedXML.Excel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TP_Labo4_Final.Models;

namespace TP_Labo4_Final.Controllers
{
    public class ImportarExController : Controller
    {
        private readonly AppDbContext _context;

      
        public ImportarExController(AppDbContext context)
        { 
            _context = context;            
        }

        // GET: ImportarExController
        public ActionResult Index()
        {
            return View();
        }

        // GET: ImportarExController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ImportarExController/Create
        public ActionResult Create()
        {
            return View();
        }

    // POST: ImportarExController/Create  

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Importar(IFormFile file)
    {
        if (file != null && file.Length > 0)
        {
            var clientes = LeerArchivoExcel(file);

            foreach (var cliente in clientes)
            {
                _context.Clientes.Add(cliente);
            }
            await _context.SaveChangesAsync();
        }

        return RedirectToAction("Index", "Clientes");
    }

    private List<Cliente> LeerArchivoExcel(IFormFile file)
    {
        var clientes = new List<Cliente>();

        using (var stream = file.OpenReadStream())
        using (var workbook = new XLWorkbook(stream))
        {
            var worksheet = workbook.Worksheet(1);
            var rows = worksheet.RowsUsed();

            foreach (var row in rows.Skip(1)) // saltar la fila de encabezado
            {
                var cliente = new Cliente
                {
                    Nombre = row.Cell(1).GetValue<string>(),
                    Apellido = row.Cell(2).GetValue<string>(),
                    Cuit = row.Cell(3).GetValue<string>(),
                    Direccion = row.Cell(4).GetValue<string>(),
                    Altura = row.Cell(5).GetValue<string>(),
                    Departamento = row.Cell(6).GetValue<string>(),
                    Piso = row.Cell(7).GetValue<string>(),
                    Localidad = row.Cell(8).GetValue<string>(),
                    Provincia = row.Cell(9).GetValue<string>(),
                    Pais = row.Cell(10).GetValue<string>(),
                    Telefono = row.Cell(11).GetValue<string>(),
                    Email = row.Cell(12).GetValue<string>(),
                    Estado = row.Cell(13).GetValue<bool>(),
                    ViajanteId = row.Cell(14).GetValue<int>()
                };

                clientes.Add(cliente);
            }
        }

        return clientes;
        }

            // GET: ImportarExController/Edit/5
            public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ImportarExController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ImportarExController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ImportarExController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

TP_Labo4_Final/Views/Clientes/Create.cshtml
@model TP_Labo4_Final.Models.Cliente

@{
    ViewData["Title"] = "Create";
}

<h1>Cargar nuevo cliente</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cuit" class="control-label"></label>
                <input asp-for="Cuit" class="form-control" />
                <span asp-validation-for="Cuit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Altura" class="control-label"></label>
                <input asp-for="Altura" class="form-control" />
                <span asp-validation-for="Altura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Departamento" class="control-label"></label>
                <input asp-for="Departamento" class="form-control" />
                <span asp-validation-for="Departamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Piso" class="control-label"></label>
                <input asp-for="Piso" class="form-control" />
                <span asp-validation-for="Piso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Localidad" class="control-label"></label>
                <input asp-for="Localidad" class="form-control" />
                <span asp-validation-for="Localidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Provincia" class="control-label"></label>
                <input asp-for="Provincia" class="form-control" />
                <span asp-validation-for="Provincia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pais" class="control-label"></label>
                <input asp-for="Pais" class="form-control" />
                <span asp-validation-for="Pais" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Viajante" class="control-label"></label>
                <select asp-for="ViajanteId" class="form-control" asp-items="ViewBag.ViajanteId"></select>
                <span asp-validation-for="ViajanteId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                </label>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TP_Labo4_Final/Views/Clientes/Delete.cshtml
@model TP_Labo4_Final.Models.Cliente

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cuit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cuit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Altura)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Altura)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Piso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Piso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Localidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Localidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Provincia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Provincia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pais)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pais)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TP_Labo4_Final/Views/Clientes/Details.cshtml
@model TP_Labo4_Final.Models.Cliente

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cuit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cuit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Altura)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Altura)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Piso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Piso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Localidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Localidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Provincia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Provincia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pais)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pais)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            Viajante
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Viajante!.Nombre) @Html.DisplayFor(model => model.Viajante!.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Editar</a> |
    <a asp-action="Index">Volver a la lista</a> |
    <a asp-action="Delete" asp-route-id="@Model?.Id">Eliminar</a>
</div>

TP_Labo4_Final/Views/Clientes/Edit.cshtml
@model TP_Labo4_Final.Models.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cuit" class="control-label"></label>
                <input asp-for="Cuit" class="form-control" />
                <span asp-validation-for="Cuit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Altura" class="control-label"></label>
                <input asp-for="Altura" class="form-control" />
                <span asp-validation-for="Altura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Departamento" class="control-label"></label>
                <input asp-for="Departamento" class="form-control" />
                <span asp-validation-for="Departamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Piso" class="control-label"></label>
                <input asp-for="Piso" class="form-control" />
                <span asp-validation-for="Piso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Localidad" class="control-label"></label>
                <input asp-for="Localidad" class="form-control" />
                <span asp-validation-for="Localidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Provincia" class="control-label"></label>
                <input asp-for="Provincia" class="form-control" />
                <span asp-validation-for="Provincia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pais" class="control-label"></label>
                <input asp-for="Pais" class="form-control" />
                <span asp-validation-for="Pais" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Viajante" class="control-label"></label>
                <select asp-for="ViajanteId" class="form-control" asp-items="ViewBag.ViajanteId"></select>
                <span asp-validation-for="ViajanteId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TP_Labo4_Final/Views/Clientes/Index.cshtml
@* @model IEnumerable<TP_Labo4_Final.Models.Cliente> *@
@* //Se cambia la referencia del model para poder usar el paginador *@
@model Paginador<TP_Labo4_Final.Models.Cliente>
@{
    ViewData["Title"] = "Clientes";
}

<h1>Clientes</h1>

<form method="get">
    <div class="row mb-2">
        <div class="col-md-8">
            <input type="text" name="searchString" class="form-control" value="@ViewData["searchString"]" placeholder="Buscar cliente..." />
        </div>
        <div class="col-md-4">
            <button type="submit" class="btn btn-primary">Buscar</button>
        </div>
    </div>
</form>
<br />
<p>
    <a asp-action="Create" class="btn btn-success">Cargar nuevo cliente</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Elementos.First().Nombre)</th>
            <th>@Html.DisplayNameFor(model => model.Elementos.First().Apellido)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Elementos)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                <td>@Html.DisplayFor(modelItem => item.Apellido)</td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Detalle</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@* Paginador *@
<div>
    @if (Model.HayPaginaAnterior)
    {
        <a asp-action="Index" asp-route-pagina="@(Model.PaginaActual - 1)" asp-route-searchString="@ViewData["searchString"]">Anterior</a>
    }

    Página @Model.PaginaActual de @Model.TotalPaginas

    @if (Model.HayPaginaSiguiente)
    {
        <a asp-action="Index" asp-route-pagina="@(Model.PaginaActual + 1)" asp-route-searchString="@ViewData["searchString"]">Siguiente</a>
    }
</div>

<hr />
<form asp-controller="ImportarEx" asp-action="Importar" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="file" style="font-size: 1.30em">Importar clientes desde archivo Excel:</label>
        <input type="file" name="file" class="form-control" />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Importar</button>
</form>
<hr />